services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eygarproperty
    env_file:
      - ./.env
    environment:
      PYTHONUNBUFFERED: "1"
    ports:
      - "8001:8001"
    restart: unless-stopped
