services:
  postgres:
    image: postgres:15-alpine
    container_name: listing_service_db
    environment:
      POSTGRES_USER: listing_user
      POSTGRES_PASSWORD: listing_password
      POSTGRES_DB: listing_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listing_user -d listing_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: listing_service_redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: