"""Add coupons table

Revision ID: 52cdf1a0e49c
Revises: da569ab6c9ac
Create Date: 2025-10-30 14:05:53.349081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52cdf1a0e49c'
down_revision = 'da569ab6c9ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('serviceId', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('discountType', sa.String(), nullable=False),
    sa.Column('discountValue', sa.Float(), nullable=False),
    sa.Column('validFrom', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validTo', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usageLimit', sa.Integer(), nullable=False),
    sa.Column('usedCount', sa.Integer(), nullable=True),
    sa.Column('eligibility', sa.String(), nullable=True),
    sa.Column('terms', sa.String(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['serviceId'], ['vendor_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_serviceId'), 'coupons', ['serviceId'], unique=False)
    op.alter_column('vendor_services', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('vendor_services', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_services', 'reviewCount',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_services', 'createdAt',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_services', 'createdAt',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vendor_services', 'reviewCount',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_services', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('vendor_services', 'isActive',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_coupons_serviceId'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    # ### end Alembic commands ###
