"""added category to properties

Revision ID: 99fc2e39eb54
Revises: dcb94415f40c
Create Date: 2025-10-15 16:13:34.649435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99fc2e39eb54'
down_revision = 'dcb94415f40c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('category', sa.String(), nullable=True))
    op.create_index(op.f('ix_properties_category'), 'properties', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_category'), table_name='properties')
    op.drop_column('properties', 'category')
    # ### end Alembic commands ###
