"""Update rules and added cancellationpolicy table

Revision ID: 11248732b3b4
Revises: b3bf335fae93
Create Date: 2025-12-11 13:37:21.650355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11248732b3b4'
down_revision = 'b3bf335fae93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellation_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('free_cancel_days_before_checkin', sa.Integer(), nullable=False),
    sa.Column('partial_refund_days_before_checkin', sa.Integer(), nullable=True),
    sa.Column('partial_refund_percentage', sa.Integer(), nullable=True),
    sa.Column('no_refund_inside_hours_before_checkin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('properties', sa.Column('cancellation_policy_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'properties', 'cancellation_policies', ['cancellation_policy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'cancellation_policy_id')
    op.drop_table('cancellation_policies')
    # ### end Alembic commands ###
