"""Initial migration with all models

Revision ID: c4eace5a4ecd
Revises: 0e5cb956203f
Create Date: 2025-09-30 13:02:36.402465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4eace5a4ecd'
down_revision = '0e5cb956203f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
