"""add experiences feature

Revision ID: dda0b7bd423c
Revises: dfe6e023e07f
Create Date: 2025-10-05 15:42:41.499500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda0b7bd423c'
down_revision = 'dfe6e023e07f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('min_nights', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_experience_host_active', 'experiences', ['host_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_experiences_host_id'), 'experiences', ['host_id'], unique=False)
    op.create_index(op.f('ix_experiences_id'), 'experiences', ['id'], unique=False)
    op.create_index(op.f('ix_experiences_is_active'), 'experiences', ['is_active'], unique=False)
    op.create_table('property_experiences',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id', 'experience_id')
    )
    op.create_index('idx_property_experiences_experience', 'property_experiences', ['experience_id'], unique=False)
    op.create_index('idx_property_experiences_property', 'property_experiences', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_property_experiences_property', table_name='property_experiences')
    op.drop_index('idx_property_experiences_experience', table_name='property_experiences')
    op.drop_table('property_experiences')
    op.drop_index(op.f('ix_experiences_is_active'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_id'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_host_id'), table_name='experiences')
    op.drop_index('idx_experience_host_active', table_name='experiences')
    op.drop_table('experiences')
    # ### end Alembic commands ###
