"""fix default value for float fields

Revision ID: b3bf335fae93
Revises: 03f9f8da7be9
Create Date: 2025-12-08 10:39:35.447323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bf335fae93'
down_revision = '03f9f8da7be9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
