"""Change coupons id column to UUID type

Revision ID: 846cfa7e8aae
Revises: 52cdf1a0e49c
Create Date: 2025-10-30 14:34:29.121537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846cfa7e8aae'
down_revision = '52cdf1a0e49c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupons', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupons', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='id::varchar')
    # ### end Alembic commands ###
