"""added tags to properties

Revision ID: dcb94415f40c
Revises: dda0b7bd423c
Create Date: 2025-10-15 15:47:21.283039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb94415f40c'
down_revision = 'dda0b7bd423c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'tags')
    # ### end Alembic commands ###
