"""Update property table with is_owner and is_agent

Revision ID: 3767da35b896
Revises: 11248732b3b4
Create Date: 2026-01-05 14:54:06.205903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3767da35b896'
down_revision = '11248732b3b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    revenue_share_enum = postgresql.ENUM(
        "fixed",
        "percentage",
        "hybrid",
        name="revenuesharetype"
    )
    revenue_share_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "properties",
        sa.Column(
            "revenue_share_type",
            revenue_share_enum,
            nullable=True,
        ),
    )

    op.add_column('properties', sa.Column('is_owner', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('is_agent', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('revenue_share', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'revenue_share')
    op.drop_column('properties', 'revenue_share_type')
    op.drop_column('properties', 'is_agent')
    op.drop_column('properties', 'is_owner')
    # ### end Alembic commands ###
